@baseUrl = http://localhost:3001
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@mailinator.com",
  "password": "qwer1234",
  "accessRoles": "LEADER"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "jane.doe@mailinator.com",
  "password": "qwer1234"
}

###

# @name create_game
POST {{baseUrl}}/games
Content-Type: application/json
Authorization: Bearer {{authToken}}