version: '3.8'

services:
  postgres:
    container_name: pixel_hub_pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pixel_hub_db
    volumes:
      - ./data/pg:/data/postgres